image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-browser

tasks:
  - before: bash .gp/bash/before-tasks.sh
    init: |
      composer install --no-dev
    name: Main Terminal
  - openMode: split-right
    command: |
      php -S 0.0.0.0:8000 -t ./
    name: Web Server

vscode:
  extensions:
    - felixfbecker.php-debug